name: Build ClipBox MSIX

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Create Windows project
        run: flutter create --platforms=windows .

      - name: Copy application icon
        run: copy windows_config\resources\app_icon.ico windows\runner\resources\app_icon.ico

      - name: Build Windows application
        run: flutter build windows --release

      - name: Create MSIX package
        run: dart run msix:create

      - name: Upload MSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: ClipBox-msix
          path: build/windows/x64/runner/Release/*.msix
